name: 'Deploy ArgoCD'
description: 'Deploy on Kubernetes with ArgoCD'
author: hello@cloudposse.com
branding:
  icon: 'cpu'
  color: 'white'
inputs:
  cluster:
    description: Cluster name
    required: true
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  helmfile-path:
    description: The path where lives the helmfile.
    required: false
    default: deploy
  helmfile:
    description: Helmfile name
    required: false
    default: helmfile.yaml
  operation:
    description: Operation with helmfiles. (valid options - `deploy`, `destroy`)
    required: true
    default: deploy
  environment:
    description: Helmfile environment
    required: false
    default: preview
  gitref-sha:
    description: Git SHA
    required: false
    default: ''
  namespace:
    description: Kubernetes namespace
    required: true
  image:
    description: Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  debug:
    description: Debug mode
    default: 'false'
    required: false
  release_label_name:
    description: The name of the label used to describe the helm release
    default: "release"
    required: false
outputs:
  webapp-url:
    description: "Web Application url"
    value: "https://example.com"
runs:
  using: "composite"
  steps:
    - name: AWS Get caller identity
      shell: bash
      run: |
        aws sts --region {{ inputs.aws-region }} get-caller-identity

